Neos:
  Neos:
    Ui:
      resources:
        stylesheets:
          'Sitegeist.Kaleidoscope.SvgDimensions':
            resource: 'resource://Sitegeist.Kaleidoscope.SvgDimensions/Public/NeosUserInterface/AdjustImageEditor.css'
            position: 'end 100'
